project:
  type: website

website:
  title: "Build the System: Hands-On Modelling with MATLAB & Simulink"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: workshop/index.qmd
        text: Workshop

  sidebar:
    - title: "Workshop"
      style: "docked"
      contents:
        - workshop/index.qmd
        - workshop/setup.qmd
        - workshop/control-systems.qmd
        - workshop/power-systems.qmd

format:
  html:
    theme: cosmo
    toc: true




