---
title: "Control Systems Task"
---

## Goal

TBD

## Task 1

Start with the state-space representation. 
To create an LTI object in state-space form, use the ss() function. 
In MATLAB, you can easily create a state-space representation of a LTI system using the following syntax:

sys = ss(A,B,C,D)

The state-space representation of the vehicle's dynamics:

img1

The variables m and b are already defined in the live script.

### Step 1
Create the A, B, C, and D matrices as follows:

A = [0 1; 0 -b/m]

B = [0; 1/m]

C = [1 0]

D = 0

 
Then, use the ss() function to create a variable vehicle_ss that stores the state-space representation of the vehicle's longitudinal dynamics.

### Step 2

To evaluate the system behaviour, apply a unit step force input.

A step input represents a sudden application of constant force at time 
𝑡 = 0.

img2

In MATLAB, you can use the step(sys) function to compute and visualize a system's response to a step input signal. 
Specifically, this function will plot the system's response to a unit step input signal that changes from 0 to 1 at time 0 second.

Compute and visualize the step response of the vehicle using the variable vehicle_ss.

### Step 3

To limit the simulation to the first 10 seconds:
[y, tout] = step(vehicle_ss, 10);

You can also scale the response signal and use the plot() function to show the response:

plot(tout, 500*y)

[Download Task 1 File](https://drive.google.com/file/d/1xIV0tdpnsgsjFuwiDaFt31VrheBPaeOy/view?usp=sharing){.btn .btn-primary} 

## Task 2

In the previous exercise, you modelled the vehicle body dynamics using a state-space representation.

Now we extend the model by including a simplified motor dynamics model. Similar to the vehicle body, the motor can also be modeled as an LTI system. Let's assume, without going into the mathematical derivations, that the transfer function of the motor is:
Gm(s)= 8/(2s+1)

### Step 1
To model an LTI system as a transfer function in MATLAB, use the tf() function. 
This function expects two inputs: the coefficients of the numerator and denominator of the transfer function, respectively, in descending order of the Laplace variable s.
 
For example, to model the transfer function

G(s)=(s+2s)/(2+3s),

type the following command:

num = [1 2];

den = [2 3];

sys = tf(num,den)

To implement a transfer function in MATLAB, use the `tf()` function.

### Step 2
The overall system consists of:

Motor → Vehicle Body

When two LTI systems are connected in series, their transfer functions multiply.

In MATLAB, you can combine systems using either:

sys = sys1 * sys2

or

sys = series(sys1, sys2)

img3

Connect the LTI models motor_tf and vehicle_ss in series. Assign the result to the variable plant.

### Step 3
To study the inherent dynamics of the complete plant, compute the impulse response.

An impulse input (Dirac delta) represents a very short burst of force applied at time 𝑡=0.

Use:

impulse(sys)

To limit the time window:
impulse(sys, 10)

Compute and visualize the plant's impulse response using the impulse() function.

[Download Task 2 File](https://drive.google.com/file/d/195fsBEs0avXXwwhFZh7dUAQFiPDEU6Cy/view?usp=sharing){.btn .btn-primary}

## Task 3
### Step 1
Once the plant is modelled, the next step in the control loop is to model the controller. A practical approach is to define the controller by choosing its pole and zero locations, which leads to a zero-pole-gain representation. In MATLAB, this type of LTI model is created using the zpk() function.
 
For instance, if an LTI system has a zero at −5, poles at −2±6i, and a scalar gain of 0.5, you can create the object using the following commands:

z = 5;

p = [-2+6i -2-6i];

k = 0.5;

sys = zpk(z, p, k)

This results in the following transfer function:

img4

Create a zero-pole-gain model for the controller with the following specifications:
•	A zero at -0.5
•	Poles at [-2+3i; -2-3i]
•	A scalar gain of 5

Assign the result to the variable controller.

### Step 2
You can now combine the controller and the plant to form the open-loop system. In MATLAB, the * operator is used to connect LTI models in series.

img5

Connect the plant and controller models in series and store the resulting open-loop system in the variable openLoopPlant.


### Step 3
The last step is to close the control loop. In MATLAB, this is done using the `feedback()` function, which connects two LTI systems in a feedback configuration and assumes negative feedback by default.
 
To build the feedback loop, use the following syntax:
openLooplant = series(controller, plant);   

Assume a unity feedback sensor (gain = 1, negative feedback by default):

closedLooplant = feedback(openLooplant, 1)

Plot a step response:
step(closedLooplant)
grid on
title("Closed-loop step response")

[Download Task 3 File](https://drive.google.com/file/d/1lLOku9UcpunbaFNN8dwkZ2R0wKjXkRgV/view?usp=sharing){.btn .btn-primary}


👉 Next: [Circuit Simulation](circuit-simulation.qmd)
