---
title: "Power Simulation Task"
---

## Goal

Task 1 and 2 touches basic circuit elements using DC source. Then we move to getting  used to AC systems and dig deeper into core concepts.

## Task 1

We will create a simple RLC circuit first to get used to the library and components.
Every Simscape model needs two blocks: a reference block and a Solver Configuration block. Electrical ground is represented by the Electrical Reference block in the Electrical domain.

To your model, add an Electrical Reference block (Simscape > Foundation Library > Electrical > Electrical Elements) and a Solver Configuration block (Simscape > Utilities).

From Simscape > Foundation Library > Electrical, add the following blocks along with their values.

• DC Voltage Source (Electrical Sources): 20 V

• Resistor (Electrical Elements): 15 ohm

• Capacitor (Electrical Elements): 2e-5 F

• Inductor (Electrical Elements): 3e-3 H

Connect the blocks to create a series RLC circuit. Add a Voltage sensor, PS-simulink converter and a scope.

img 11

The default Stop Time for a Simulink model is 10 seconds. However, the time constant for this model is

τ = RC = 10⁻⁴ sec.

Using the Simulink toolstrip, set the Stop Time to 4e-3.

[Download Task 1 File](https://drive.google.com/file/d/1B1AguTqJaQ90lwmhiL34lKdF65TDpyYX/view?usp=sharing){.btn .btn-primary}
 
## Task 2
A fundamental circuit consisting of four diodes is the bridge rectifier. The terminals seen in the drawing receive a sinusoidal input.

Current can only flow in one direction through the diode. As a result, for both positive and negative input voltage values, the terminal marked (+) receives a positive current. A corrected sine wave is the end product. 

To know about rectifiers: https://www.allaboutcircuits.com/textbook/semiconductors/chpt-3/rectifier-circuits/

Check out the diagram and make the connections.

img12

The components and some of their values used are:
• AC Voltage Source (Electrical Sources): 240*sqrt(2) V

• Resistor (Electrical Elements): 100 ohm

• Capacitor (Electrical Elements): 1600 uF

• 4 Diodes (Electrical Elements)

• Voltage sensor, PS-Simulink converter, Scope, Electrical reference and Solver configuration

Set the Stop time to 2/50 to depict 2 cycles and 50Hz.

[Download Task 2 File](https://drive.google.com/file/d/1pjbOQMs2LdIBNsrY0S5la68ZYEQlXRBn/view?usp=sharing){.btn .btn-primary}

[Download Task 2 extended file showing transformer](https://drive.google.com/file/d/11oHFdxTDyAsKT1syLFKXT4jJqVi6oR5W/view?usp=sharing){.btn .btn-primary}

## Task 3

Step 1

Add the following blocks and connect them to create a circuit in which a three-phase voltage source drives a three-phase load. The ~2 port of the load should be connected to electrical ground.

From the Simscape > Electrical > Connectors & References library:

Electrical Reference

Grounded Neutral (Three-Phase)

Simscape > Electrical > Sources:

Voltage Source (Three-Phase)

Simscape > Electrical > Passive > RLC Assemblies:

RLC (Three-Phase)

For future tasks, unless otherwise specified, block libraries will be referred to as relative to the Simscape > Electrical library. For example: Add the RLC (Three-Phase) block from Passive > RLC Assemblies library.

img 13

Step 2

On the Voltage Source (Three-Phase) block, set the Rated voltage (phase-to-phase RMS) to 120 V.

Set the Resistance of the RLC (Three-Phase) block to 15 Ohm.

Change the Modeling option of the Voltage Source (Three-Phase) to Expanded three-phase ports.
The block icon will change. The two blocks are automatically disconnected because a single-phase port cannot be connected to a three-phase port.

Change the Electrical connection of the RLC (Three-Phase) block to Expanded three-phase ports.

Connect the a, b, and c phases of the blocks Voltage Source (Three-Phase) and RLC (Three-Phase).

Add a Phase Splitter block and use it to connect the RLC (Three-Phase) block to the Grounded Neutral (Three-Phase) block.

Attach a voltage sensor across A and connect its third terminal with PS-simulink converter. Connect the converter with a scope. 

img 14

## Task 4



