---
title: "Power Simulation Task"
---

## Goal

Task 1 and 2 touches basic circuit elements using DC source. Then we move to getting  used to AC systems and dig deeper into core concepts.

## Task 1

We will create a simple RLC circuit first to get used to the library and components.
Every Simscape model needs two blocks: a reference block and a Solver Configuration block. Electrical ground is represented by the Electrical Reference block in the Electrical domain.

To your model, add an Electrical Reference block (Simscape > Foundation Library > Electrical > Electrical Elements) and a Solver Configuration block (Simscape > Utilities).

From Simscape > Foundation Library > Electrical, add the following blocks along with their values.

• DC Voltage Source (Electrical Sources): 20 V

• Resistor (Electrical Elements): 15 ohm

• Capacitor (Electrical Elements): 2e-5 F

• Inductor (Electrical Elements): 3e-3 H

Connect the blocks to create a series RLC circuit. Add a Voltage sensor, PS-simulink converter and a scope.

img 11

The default Stop Time for a Simulink model is 10 seconds. However, the time constant for this model is

τ = RC = 10⁻⁴ sec.

Using the Simulink toolstrip, set the Stop Time to 4e-3.

[Download Task 1 File](https://drive.google.com/file/d/1B1AguTqJaQ90lwmhiL34lKdF65TDpyYX/view?usp=sharing){.btn .btn-primary}
 
## Task 2
A fundamental circuit consisting of four diodes is the bridge rectifier. The terminals seen in the drawing receive a sinusoidal input.

Current can only flow in one direction through the diode. As a result, for both positive and negative input voltage values, the terminal marked (+) receives a positive current. A corrected sine wave is the end product. 

To know about rectifiers: https://www.allaboutcircuits.com/textbook/semiconductors/chpt-3/rectifier-circuits/

Check out the diagram and make the connections.

img12

The components and some of their values used are:
• AC Voltage Source (Electrical Sources): 240*sqrt(2) V

• Resistor (Electrical Elements): 100 ohm

• Capacitor (Electrical Elements): 1600 uF

• 4 Diodes (Electrical Elements)

• Voltage sensor, PS-Simulink converter, Scope, Electrical reference and Solver configuration

Set the Stop time to 2/50 to depict 2 cycles and 50Hz.

[Download Task 2 File](https://drive.google.com/file/d/1pjbOQMs2LdIBNsrY0S5la68ZYEQlXRBn/view?usp=sharing){.btn .btn-primary}

[Download Task 2 extended file showing transformer](https://drive.google.com/file/d/11oHFdxTDyAsKT1syLFKXT4jJqVi6oR5W/view?usp=sharing){.btn .btn-primary}

## Task 3

Step 1

Add the following blocks and connect them to create a circuit in which a three-phase voltage source drives a three-phase load. The ~2 port of the load should be connected to electrical ground.

From the Simscape > Electrical > Connectors & References library:

Electrical Reference

Grounded Neutral (Three-Phase)

Simscape > Electrical > Sources:

Voltage Source (Three-Phase)

Simscape > Electrical > Passive > RLC Assemblies:

RLC (Three-Phase)

For future tasks, unless otherwise specified, block libraries will be referred to as relative to the Simscape > Electrical library. For example: Add the RLC (Three-Phase) block from Passive > RLC Assemblies library.

img 13

Step 2

On the Voltage Source (Three-Phase) block, set the Rated voltage (phase-to-phase RMS) to 120 V.

Set the Resistance of the RLC (Three-Phase) block to 15 Ohm.

Change the Modeling option of the Voltage Source (Three-Phase) to Expanded three-phase ports.
The block icon will change. The two blocks are automatically disconnected because a single-phase port cannot be connected to a three-phase port.

Change the Electrical connection of the RLC (Three-Phase) block to Expanded three-phase ports.

Connect the a, b, and c phases of the blocks Voltage Source (Three-Phase) and RLC (Three-Phase).

Add a Phase Splitter block and use it to connect the RLC (Three-Phase) block to the Grounded Neutral (Three-Phase) block.

Attach a voltage sensor across A and connect its third terminal with PS-simulink converter. Connect the converter with a scope. 

img 14

[Download Task 3 File](https://drive.google.com/file/d/1ood7-E87B2zD-j2FCiA1Xh5tnkQrtdCL/view?usp=sharing){.btn .btn-primary}

## Task 4

Add a Wye-Connected Load block (Passive > RLC Assemblies) to the model. Set the Rated voltage to 240 V to match the source voltage. Change the Component structure of the Wye-Connected Load block to R-L. Leave the default value of 1e2 A*V for Inductive reactive power and Real power default value of 1e3 W.

Since the wye-connected configuration joins components together at a neutral point, the block has a single-phase port. Add an Electrical Reference block from the Connectors & References library.

Connect the blocks to power the load.

Add the following blocks to measure the phase voltage:

• Phase Voltage Sensor (Three-Phase) (Sensors & Transducers)

• Grounded Neutral (Three-Phase) (Connectors & References)

• PS-Simulink Converter (Simscape > Utilities)

• Scope (Simulink > Sinks)

Make the appropriate connections and connect the measurement to the Scope block.

Add a Power Sensor (Three-Phase) block to the model from the Sensors & Transducers library. Connect it in series with the source and load.

Create filter to lower signal distortion:

• Add a Sum block (Simulink > Math Operations) and a Discrete-Time Integrator block (Simulink > Discrete) to the model.

• Change the List of signs to |+- in order to calculate a difference. Make the connections shown to filter your measurement.

• Change the model Stop Time to 10.

• Connect the filtered measurement to another Scope via PS-Simulink converter.

img15

[Download Task 4 File](https://drive.google.com/file/d/1C9ivs5RtTE9oE2tHM28i1yYmxYIGae8s/view?usp=sharing){.btn .btn-primary}

## Task 5

Salient Pole:

• Add a Synchronous Machine Salient Pole block (Electromechanical > Synchronous) and a Wye-Connected Load block (Passive > RLC Assemblies).

• Set the Zero sequence parameter of the Synchronous Machine Salient Pole to Exclude. 

• Connect the load to the generator using the ~ ports.

• Ground the load using an Electrical Reference block (Connectors & References).

Know more about Salient Pole block: https://au.mathworks.com/help/releases/R2025a/sps/ref/synchronousmachinesalientpole.html#bt1vyu7-1_sep_mw_81ae1ff4-ce5f-418e-ac13-a1be2fffb0a2  

The microgrid will be powered by 5 MVA generators with a rated voltage of 4160 V. The active load is 2 MW. Parameterize the machine and load as listed. If a parameter is not given for a block, leave the default value.

Wye-Connected Load

• Rated voltage 4160 V.

• Real power 2e6 W.

Synchronous Machine Salient Pole

• Rated apparent power 5e6 A*V

• Rated voltage 4160 V

• Number of pole pairs 4

• Specify parameterization by Standard parameters

Set the relevant initial conditions for the Synchronous Machine Salient Pole block.

• Terminal voltage magnitude 4160 V

• Active power generated 1e6 A*V

Field circuit:

• Add the Synchronous Machine Field Circuit block (Electromechanical > Synchronous) to the model.

• Set the PS input and output unit to Per unit.

• In the Main section of the Block Parameters dialog, set the parameters to match the generator
   • Rated apparent power 5e6 A*V
   • Field circuit current 1000 A

• In the Machine Parameters section, change Specify parameterization by to Standard parameters.

• Connect the fd+ and fd- ports of the field circuit and generator blocks.

Add the following mechanical rotational blocks to your model:
• Ideal Angular Velocity Source (Simscape Foundation Library > Mechanical > Mechanical Sources)

• Mechanical Rotational Reference (Simscape Foundation Library > Mechanical > Rotational Elements)

• Machine Inertia (Electromechanical > Mechanical)

Change the Machine Inertia parameters to match the generator:

• Rated apparent power 5e6 A*V

• Number of pole pairs 4

Connect the R ports of the Ideal Angular Velocity Source and the Machine Inertia blocks to the R port of the Synchronous Machine Salient Pole block.

Connect the Mechanical Rotational Reference block to the C ports of the source and generator.

If you have not already done so, connect the Solver Configuration block to the physical network.

Constants:
• Add two Constant blocks (Simulink > Sources) and two Simulink-PS Converter blocks to your model.

• Connect the blocks to drive the field circuit and the angular velocity input.

• Set the Constant value for the block driving the field circuit to 4.5.

• Set the Constant value for the block driving the angular velocity to 2*pi*60/4 (60 Hz frequency and 4 pole pairs).

• It is good practice to set the units for the Simulink-PS Converter blocks. The inputs are 1 (since per-unit is unitless) for the field circuit and rad/s for the angular velocity.

Add a Synchronous Machine Measurement block and a PS-Simulink Converter block to your model.

Double-click the block and choose Real power as the Output.

Connect the measurement to the pu port of the generator and the Scope.

img16

[Download Task 5 File](https://drive.google.com/file/d/1B_Xka3erDYYYdd3Zejul781kKbkM_Y2X/view?usp=sharing){.btn .btn-primary}

## Microgrid

Till now, you have gone through some of the basic components that makes up a microgrid. To understand how the system works, go through the following concepts:

• AC droop control: https://au.mathworks.com/discovery/droop-control.html

• Maximum Power Point Tracking: https://www.solarquotes.com.au/inverters/mppt/

• DC to AC inverter: https://www.youtube.com/watch?v=z6gJG63Ft7o 

Let's explore a microgrid together..

[Download File](https://drive.google.com/file/d/1WH21CPEYOfh1KgJCo6WH0L80nHmBfEsj/view?usp=sharing){.btn .btn-primary}
